//! Git binary diffs support.
//!
//! This module provides parsing and decoding for Git's binary diff format,
//! as generated by `git diff --binary` or `git format-patch --binary`.
//!
//! Based on [DiffX Binary Diffs specification](https://diffx.org/spec/binary-diffs.html).

#[cfg(feature = "binary")]
mod base85;
#[cfg(feature = "binary")]
mod delta;

use std::borrow::Cow;
use std::fmt;

/// A parsed binary patch.
///
/// A binary patch contains encoded binary data that can be decoded
/// to recover the original and modified file contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BinaryPatch<'a> {
    /// [Git Literal binary diffs](https://diffx.org/spec/binary-diffs.html#git-literal-binary-diffs)
    /// contain the full contents of both the original and modified binary files,
    /// zlib-compressed and encoded as Base85.
    Literal {
        /// Modified file content.
        modified: BinaryData<'a>,
        /// Original file content.
        original: BinaryData<'a>,
    },
    /// [Git Delta binary diffs](https://diffx.org/spec/binary-diffs.html#git-delta-binary-diffs)
    /// contain instructions on applying patches to binary files.
    ///
    /// Unlike [`BinaryPatch::Literal`],
    /// these do not require embedding the full content of the new file in the patch.
    Delta {
        /// Delta instructions: original -> modified.
        forward: BinaryData<'a>,
        /// Delta instructions: modified -> original.
        reverse: BinaryData<'a>,
    },
    /// A Git binary diff marker.
    ///
    /// This represents the `Binary files a/path and b/path differ` case,
    /// where git detected a binary change but didn't include the actual data
    ///
    /// Calling [`apply()`](Self::apply) on this variant returns an error.
    Marker,
}

impl<'a> BinaryPatch<'a> {
    /// Applies a binary patch forward: original -> modified.
    ///
    /// For [`Literal`](BinaryPatch::Literal),
    /// returns the embedded modified content.
    /// Unlike `git apply`,
    /// this doesn't check integrity of `original` but directly decodes and applies.
    ///
    /// For [`Delta`](BinaryPatch::Literal),
    /// applies forward delta instructions to `original`.
    #[cfg(feature = "binary")]
    pub fn apply(&self, original: &[u8]) -> Result<Vec<u8>, BinaryPatchParseError> {
        match self {
            BinaryPatch::Literal { modified, .. } => Self::decode_data(modified),
            BinaryPatch::Delta { forward, .. } => {
                let delta_instructions = Self::decode_data(forward)?;
                delta::apply(original, &delta_instructions)
                    .map_err(|e| BinaryPatchParseError::new(e.to_string()))
            }
            BinaryPatch::Marker => Err(BinaryPatchParseError::new("no binary data available")),
        }
    }

    /// Applies a binary patch in reverse: modified -> original.
    ///
    /// For [`Literal`](BinaryPatch::Literal),
    /// returns the embedded original content.
    /// Unlike `git apply`,
    /// this doesn't check integrity of `modified` but directly decodes and applies.
    ///
    /// For [`Delta`](BinaryPatch::Delta),
    /// applies reverse delta instructions to `modified`.
    #[cfg(feature = "binary")]
    pub fn apply_reverse(&self, modified: &[u8]) -> Result<Vec<u8>, BinaryPatchParseError> {
        match self {
            BinaryPatch::Literal { original, .. } => Self::decode_data(original),
            BinaryPatch::Delta { reverse, .. } => {
                let delta_instructions = Self::decode_data(reverse)?;
                delta::apply(modified, &delta_instructions)
                    .map_err(|e| BinaryPatchParseError::new(e.to_string()))
            }
            BinaryPatch::Marker => Err(BinaryPatchParseError::new("no binary data available")),
        }
    }

    /// See [Decoding Logic](https://diffx.org/spec/binary-diffs.html#decoding-logic)
    #[cfg(feature = "binary")]
    fn decode_data(binary_data: &BinaryData<'_>) -> Result<Vec<u8>, BinaryPatchParseError> {
        use std::io::Read;

        let compressed = decode_base85_lines(binary_data.data)?;

        let mut decoder = flate2::read::ZlibDecoder::new(&compressed[..]);
        let mut decompressed = Vec::new();
        decoder
            .read_to_end(&mut decompressed)
            .map_err(|e| BinaryPatchParseError::new(format!("decompression failed: {e}")))?;

        Ok(decompressed)
    }
}

/// Represents a single binary payload in a Git binary diff.
///
/// For example, the following patch block
///
/// * is parsed as `BinaryData { size: 10, data: "UcmV+l0QLU>0RjUA1qKHQ2>\`DEE&u=k" }`
/// * The line starts with a length indicator (`U` = 21 decoded bytes)
///
///
/// ```text
/// literal 10
/// UcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryData<'a> {
    /// Uncompressed size in bytes.
    pub size: u64,
    /// Raw Base85 lines with length indicators.
    pub data: &'a str,
}

/// Simple streaming parser for binary patches using lines() iterator.
struct BinaryParser<'a> {
    input: &'a str,
    offset: usize,
}

impl<'a> BinaryParser<'a> {
    fn new(input: &'a str) -> Self {
        Self { input, offset: 0 }
    }

    fn peek_line(&self) -> Option<&'a str> {
        self.input[self.offset..].lines().next()
    }

    fn next_line(&mut self) -> Option<&'a str> {
        let rest = &self.input[self.offset..];
        let line = rest.lines().next()?;
        self.offset += line.len();

        // Skip line ending (CRLF or LF)
        let remaining = &self.input[self.offset..];
        if remaining.starts_with("\r\n") {
            self.offset += 2;
        } else if remaining.starts_with('\n') {
            self.offset += 1;
        }

        Some(line)
    }

    fn slice_from(&self, start_offset: usize) -> &'a str {
        let end = self.offset;
        // Strip trailing line ending before blank line
        let slice = &self.input[start_offset..end];
        slice
            .strip_suffix("\r\n")
            .or_else(|| slice.strip_suffix('\n'))
            .unwrap_or(slice)
    }
}

/// Parses binary patch content after git extended headers.
///
/// Expects input starting with "GIT binary patch" line.
///
/// Format:
///
/// ```text
/// GIT binary patch
/// <literal|delta> <modified_size>
/// <base85_lines>
///
/// <literal|delta> <original_size>
/// <base85_lines>
/// ```
pub(crate) fn parse_binary_patch(input: &str) -> Result<BinaryPatch<'_>, BinaryPatchParseError> {
    let mut parser = BinaryParser::new(input);

    // Expect "GIT binary patch" marker
    assert_eq!(parser.next_line(), Some("GIT binary patch"));

    // Parse first block (modified content or forward delta)
    let Some((first_type, first_data)) = parse_binary_block(&mut parser) else {
        return Err(BinaryPatchParseError::new("first binary block not found"));
    };

    // Parse second block (original content or reverse delta)
    let Some((second_type, second_data)) = parse_binary_block(&mut parser) else {
        return Err(BinaryPatchParseError::new("second binary block not found"));
    };

    let patch = match first_type {
        "literal" => BinaryPatch::Literal {
            modified: first_data,
            original: second_data,
        },
        "delta" => BinaryPatch::Delta {
            forward: first_data,
            reverse: second_data,
        },
        _ => {
            return Err(BinaryPatchParseError::new("unrecognized binary patch type"));
        }
    };

    // Both blocks must have the same type
    if first_type != second_type {
        return Err(BinaryPatchParseError::new(
            "binary data blocks must be the same",
        ));
    }

    Ok(patch)
}

/// Parses a single binary block.
///
/// Returns `(patch_type, size, data)` where data is a slice of Base85 lines.
fn parse_binary_block<'a>(parser: &mut BinaryParser<'a>) -> Option<(&'a str, BinaryData<'a>)> {
    // Parse "literal 10" or "delta 18"
    let format_line = parser.next_line()?;
    let (patch_type, size_str) = format_line.split_once(' ')?;
    let size: u64 = size_str.parse().ok()?;

    // Record start of Base85 data
    let data_start = parser.offset;

    // Consume Base85 lines until blank line
    while let Some(line) = parser.peek_line() {
        if line.is_empty() {
            parser.next_line(); // Consume blank line
            break;
        }
        parser.next_line();
    }

    let data = parser.slice_from(data_start);

    let data = BinaryData { size, data };
    Some((patch_type, data))
}

/// Decodes multi-line Base85 data with length indicators.
///
/// Each line has the format: `<len_c><data>`
///
/// From [5.1.1. Binary Payloads](https://diffx.org/spec/binary-diffs.html#binary-payloads):
///
/// > Each line represents up to 52 bytes of pre-encoded data.
/// > There may be an unlimited number of lines.
/// > They contain the following fields:
/// >
/// >  * `len_c` is a line length character.
/// >     This encodes the length of the (pre-encoded) data written on this line.
/// >  * `data` is Base85-encoded data for this line.
#[cfg(feature = "binary")]
fn decode_base85_lines(data: &str) -> Result<Vec<u8>, BinaryPatchParseError> {
    // A rough estimate: In Base85, 5 chars -> 4 bytes
    let mut result = Vec::with_capacity(data.len() * 4 / 5);

    for line in data.lines() {
        if line.is_empty() {
            continue;
        }

        let line_bytes = line.as_bytes();

        let length = decode_line_length(line_bytes[0])
            .ok_or_else(|| BinaryPatchParseError::new("invalid line length indicator"))?;
        let encoded = &line[1..];
        let start = result.len();
        base85::decode_into(encoded, &mut result)
            .map_err(|e| BinaryPatchParseError::new(e.to_string()))?;
        result.truncate(start + length);
    }

    Ok(result)
}

/// Decodes a line length character to its numeric value.
///
/// From [Line Length Characters](https://diffx.org/spec/binary-diffs.html#line-length-characters):
///
/// > Each encoded line in a binary diff payload is prefixed by a line length character.
/// > This encodes the length of the compressed (but not encoded) data for the line.
/// >
/// > Line length characters always represent a value between 1 and 52:
/// >
/// > * A value of A-Z represents a number between 1..26.
/// > * A value of a-z represents a number between 27..52.
#[cfg(feature = "binary")]
fn decode_line_length(c: u8) -> Option<usize> {
    match c {
        b'A'..=b'Z' => Some((c - b'A' + 1) as usize),
        b'a'..=b'z' => Some((c - b'a' + 27) as usize),
        _ => None,
    }
}

/// Error type for binary patch operations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryPatchParseError(Cow<'static, str>);

impl BinaryPatchParseError {
    pub(crate) fn new<E: Into<Cow<'static, str>>>(e: E) -> Self {
        Self(e.into())
    }
}

impl fmt::Display for BinaryPatchParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for BinaryPatchParseError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_literal_format_simple() {
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\nliteral 0\nKcmV+b0RR6000031\n\n";
        let patch = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Literal { modified, original } => {
                assert_eq!(modified.size, 10);
                assert_eq!(original.size, 0);
            }
            _ => panic!("expected Literal variant"),
        }
    }

    #[test]
    fn parse_delta_format() {
        let input = "GIT binary patch\ndelta 18\nccmV+t0PX*P2!IH%^Z^9`00000v-trB0x!=5aR2}S\n\ndelta 18\nccmV+t0PX*P2!IH%^Z^BFm9#}av-trB0zxAOrvLx|\n\n";
        let patch = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Delta { forward, reverse } => {
                assert_eq!(forward.size, 18);
                assert_eq!(reverse.size, 18);
            }
            _ => panic!("expected Delta variant"),
        }
    }

    #[test]
    #[should_panic(expected = "assertion")]
    fn parse_missing_marker() {
        // Without "GIT binary patch" marker, parse_binary_patch panics (debug_assert)
        let input = "literal 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\n";
        let _ = parse_binary_patch(input);
    }

    #[test]
    fn parse_with_crlf_line_endings() {
        let input = "GIT binary patch\r\nliteral 10\r\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\r\n\r\nliteral 0\r\nKcmV+b0RR6000031\r\n\r\n";
        let patch = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Literal { modified, original } => {
                assert_eq!(modified.size, 10);
                assert_eq!(original.size, 0);
            }
            _ => panic!("expected Literal variant"),
        }
    }

    #[test]
    fn parse_mixed_format_rejected() {
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\ndelta 18\nccmV+t0PX*P2!IH%^Z^9`00000v-trB0x!=5aR2}S\n\n";
        assert!(parse_binary_patch(input).is_err());
    }
}

#[cfg(test)]
#[cfg(feature = "binary")]
mod apply_tests {
    use super::*;

    #[test]
    fn decode_line_length_uppercase() {
        assert_eq!(decode_line_length(b'A'), Some(1));
        assert_eq!(decode_line_length(b'B'), Some(2));
        assert_eq!(decode_line_length(b'Z'), Some(26));
    }

    #[test]
    fn decode_line_length_lowercase() {
        assert_eq!(decode_line_length(b'a'), Some(27));
        assert_eq!(decode_line_length(b'b'), Some(28));
        assert_eq!(decode_line_length(b'z'), Some(52));
    }

    #[test]
    fn decode_line_length_invalid() {
        assert_eq!(decode_line_length(b'0'), None);
        assert_eq!(decode_line_length(b'!'), None);
        assert_eq!(decode_line_length(b' '), None);
    }

    #[test]
    fn apply_literal_patch() {
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\nliteral 0\nKcmV+b0RR6000031\n\n";
        let patch = parse_binary_patch(input).unwrap();

        let modified = patch.apply(&[]).unwrap();
        assert_eq!(modified.len(), 10);
        assert_eq!(modified, vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);

        let original = patch.apply_reverse(&[]).unwrap();
        assert_eq!(original.len(), 0);
    }

    #[test]
    fn apply_with_crlf_line_endings() {
        let input = "GIT binary patch\r\nliteral 10\r\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\r\n\r\nliteral 0\r\nKcmV+b0RR6000031\r\n\r\n";
        let patch = parse_binary_patch(input).unwrap();

        let modified = patch.apply(&[]).unwrap();
        assert_eq!(modified, vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
        let original = patch.apply_reverse(&[]).unwrap();
        assert_eq!(original.len(), 0);
    }
}
