name: CI

on:
  push:
    branches:
      - main
      - git-format-patch
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CI: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.70.0]

    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal
      - run: cargo +${{ matrix.rust }} check --all-targets --all-features
      - run: cargo +${{ matrix.rust }} test

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install stable --profile minimal --component rustfmt,clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets
      - run: cargo doc --no-deps

  replay:
    strategy:
      matrix:
        include:
          - name: diffy
            repo_url: ''
            commits: '0'
          - name: cargo
            repo_url: https://github.com/rust-lang/cargo
            commits: '200'
          - name: rust
            repo_url: https://github.com/rust-lang/rust
            commits: '30'
    name: replay (${{ matrix.name }})
    uses: ./.github/workflows/replay.yml
    with:
      repo_url: ${{ matrix.repo_url }}
      commits: ${{ matrix.commits }}
