name: CI

on:
  push:
    branches:
      - main
      - git-format-patch
  pull_request:

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.70.0]

    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal
      - run: cargo +${{ matrix.rust }} check --all-targets --all-features
      - run: cargo +${{ matrix.rust }} test

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install stable --profile minimal --component rustfmt,clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets
      - run: cargo doc --no-deps

  history-replay:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: diffy
            repo: .
            commits: 0
            parse_mode: unidiff
          - name: diffy
            repo: .
            commits: 0
            parse_mode: gitdiff
          - name: cargo
            repo: target/test-repo
            clone: https://github.com/rust-lang/cargo --depth 201
            commits: 200
            parse_mode: unidiff
          - name: cargo
            repo: target/test-repo
            clone: https://github.com/rust-lang/cargo --depth 201
            commits: 200
            parse_mode: gitdiff
          - name: rust
            repo: target/test-repo
            clone: https://github.com/rust-lang/rust --depth 31
            commits: 30
            parse_mode: unidiff
          - name: rust
            repo: target/test-repo
            clone: https://github.com/rust-lang/rust --depth 31
            commits: 30
            parse_mode: gitdiff
    name: history-replay (${{ matrix.name }}, ${{ matrix.parse_mode }})
    # GitDiff mode doesn't yet handle no-hunk patches, for example pure renames:
    #
    #     diff --git a/src/patch.rs b/src/patch/mod.rs
    #     similarity index 100%
    #     rename from src/patch.rs
    #     rename to src/patch/mod.rs
    #
    # Track progress without blocking CI.
    continue-on-error: ${{ matrix.parse_mode == 'gitdiff' }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ matrix.clone && 1 || 0 }}
      - if: matrix.clone
        run: git clone ${{ matrix.clone }} ${{ matrix.repo }}
      - run: rustup toolchain install stable --profile minimal
      - run: cargo test --release --test git_history_replay -- --nocapture
        env:
          DIFFY_TEST_REPO: ${{ matrix.repo }}
          DIFFY_TEST_COMMITS: ${{ matrix.commits }}
          DIFFY_TEST_PARSE_MODE: ${{ matrix.parse_mode }}
